### Tests Numpy.
### Auteur : Charles T.

In [1]:
%load_ext pycodestyle_magic
%pycodestyle_on

In [2]:
import numpy as np

### Matrice et fonction array

In [3]:
A = np.array(([1, 2], [3, 4]))
print('Matrice A\n\n{0}\n'.format(A))
print('{0:15}: {1}'.format('Dimension de A', A.ndim))
print('{0:15}: {1}'.format('Forme de A', A.shape))

Matrice A

[[1 2]
 [3 4]]

Dimension de A : 2
Forme de A     : (2, 2)


### Matrice et module random

In [4]:
B = np.random.randint(0, 5, size=(2, 2), dtype=np.uint8)
print('Matrice B\n\n{0}\n'.format(B))

Matrice B

[[3 4]
 [0 3]]



### Matrice et fonction ones

In [5]:
C = np.ones((3, 1))
print('Matrice C\n\n{0}\n'.format(C))

Matrice C

[[1.]
 [1.]
 [1.]]



### Matrice et fonctions linspace, reshape

In [6]:
D = np.linspace(0, 10, 5, dtype=np.int64)
print('Matrice D\n\n{0}\n'.format(D))
print('Forme de D: {0}\n'.format(D.shape))
D = D.reshape(D.shape[0], 1)
print('{0}\n\nForme de D: {1}\n'.format(D, D.shape))

Matrice D

[ 0  2  5  7 10]

Forme de D: (5,)

Matrice D

[ 0  2  5  7 10]

[[ 0]
 [ 2]
 [ 5]
 [ 7]
 [10]]

Forme de D: (5, 1)



### Matrice et fonction arange

In [7]:
E = np.arange(-10, 11, 2)
print('Matrice E\n\n{0}\n'.format(E))
print('Forme de E: {0}\n'.format(E.shape))

Matrice E

[-10  -8  -6  -4  -2   0   2   4   6   8  10]

Forme de E: (11,)



### Matrice et fonctions concatenate, reshape

In [8]:
AB = np.concatenate((A, B), axis=1)
print('Matrice AB\n\n{0}\n'.format(AB))
AB = AB.reshape(4, 2)
print('Matrice AB\n\n{0}'.format(AB))

Matrice AB

[[1 2 3 4]
 [3 4 0 3]]

Matrice AB

[[1 2]
 [3 4]
 [3 4]
 [0 3]]


### Algèbre linéaire

In [9]:
print('{0:20}\n\n {1}\n'.format('A + B', A + B))
print('{0:20}\n\n {1}\n'.format('A * B', A.dot(B)))
print('{0:20}\n\n {1}\n'.format('Transposée de A', np.transpose(A)))
print('{0:20}\n\n {1}\n'.format('Inverse de A', np.linalg.inv(A)))
print('{0:20}\n\n {1}\n'.format('Déterminant de A', np.linalg.det(A)))

A + B               

 [[4 6]
 [3 7]]

A * B               

 [[ 3 10]
 [ 9 24]]

Transposée de A     

 [[1 3]
 [2 4]]

Inverse de A        

 [[-2.   1. ]
 [ 1.5 -0.5]]

Déterminant de A    

 -2.0000000000000004



### Statistiques

In [10]:
S = np.array([3, 8, 9, 7, 6, 5, 4, 2, 1])
print('Matrice S\n\n{0}'.format(S))
S = S.reshape(3, 3)
print('\nMatrice S\n\n{0}\n'.format(S))

print('{0:40} {1}\n'.format('Somme des colonnes: ', S.sum(axis=0)))
print('{0:40} {1}\n'.format('Produit des éléments de S: ', S.prod()))
print('{0:40} {1}\n'.format('Maximums sur les lignes: ', S.max(axis=1)))
print('{0:40} {1}\n'.format('Ind max sur les lignes: ', S.argmax(axis=1)))
print('{0:40} {1}\n'.format('Maximums sur les colonnes: ', S.max(axis=0)))
print('{0:40} {1}\n'.format('Ind max sur les colonnes: ', S.argmax(axis=0)))
print('{0:40} {1}\n'.format('Moyenne de la matrice: ', S.mean()))
print('{0:40} {1}\n'.format('Variance de la matrice: ', S.var()))
print('{0:40}\n\n {1}\n'.format('Matrice de corrélation: ', np.corrcoef(S)))

Matrice S

[3 8 9 7 6 5 4 2 1]

Matrice S

[[3 8 9]
 [7 6 5]
 [4 2 1]]

Somme des colonnes:                      [14 16 15]

Produit des éléments de S:               362880

Maximums sur les lignes:                 [9 7 4]

Ind max sur les lignes:                  [2 0 0]

Maximums sur les colonnes:               [7 8 9]

Ind max sur les colonnes:                [1 0 0]

Moyenne de la matrice:                   5.0

Variance de la matrice:                  6.666666666666667

Matrice de corrélation:                 

 [[ 1.         -0.93325653 -0.98432414]
 [-0.93325653  1.          0.98198051]
 [-0.98432414  0.98198051  1.        ]]

